// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoSpares.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotoSpares.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Role_ID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("Concurrency_Stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Role_Name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Normalized_Role_Name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("MS_ROLE", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Role_Claim_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("Claim_Type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("Claim_Value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("Role_ID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("MS_ROLE_CLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("User_Claim_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("Claim_Type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("Claim_Value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MS_USER_CLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("Login_Provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("Provider_Key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("Provider_Display_Name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("MS_USER_LOGIN", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("Role_ID");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("MS_USER_ROLE", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("Login_Provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Token_Name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("Token_Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("MS_USER_TOKEN", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("Access_Failed_Count");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Address");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("Concurrency_Stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created_At");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("Email_Confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Full_Name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Lockout_Enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Lockout_End");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Normalized_Email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Normalized_User_Name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("Password_Hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("Phone_Confirmed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("Security_Stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Two_Factor_Enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("User_Name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("MS_USER", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Appointment_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Appointment_Date");

                    b.Property<string>("AppointmentNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Appointment_Notes");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Appointment_Status");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Service_Type");

                    b.HasKey("AppointmentId");

                    b.ToTable("MS_APPOINTMENT", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Notification_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("Is_Read");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Notification_Date");

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Notification_Message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Notification_Type");

                    b.HasKey("NotificationId");

                    b.ToTable("MS_NOTIFICATION", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Part_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Part_Name");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Part_Number");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer")
                        .HasColumnName("Reorder_Level");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("Stock_Quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Unit_Price");

                    b.HasKey("PartId");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("MS_PART", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PartRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Request_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Request_Date");

                    b.Property<string>("RequestDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Request_Description");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Request_Status");

                    b.Property<string>("RequestedPartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Requested_Part_Name");

                    b.HasKey("RequestId");

                    b.ToTable("MS_PART_REQUEST", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Property<int>("PurchaseInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Purchase_Invoice_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseInvoiceId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Purchase_Date");

                    b.Property<decimal>("PurchaseTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Purchase_Total");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("Vendor_ID");

                    b.HasKey("PurchaseInvoiceId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VendorId");

                    b.ToTable("MS_PURCHASE_INVOICE", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseInvoiceItem", b =>
                {
                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("Purchase_Invoice_ID");

                    b.Property<int>("PurchaseItemId")
                        .HasColumnType("integer")
                        .HasColumnName("Purchase_Item_ID");

                    b.HasKey("PurchaseInvoiceId", "PurchaseItemId");

                    b.HasIndex("PurchaseItemId");

                    b.ToTable("MS_PURCHASE_INVOICE_ITEM", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseItem", b =>
                {
                    b.Property<int>("PurchaseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Purchase_Item_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseItemId"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("Part_ID");

                    b.Property<int>("PurchaseQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("Purchase_Quantity");

                    b.Property<decimal>("PurchaseUnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Purchase_Unit_Cost");

                    b.HasKey("PurchaseItemId");

                    b.HasIndex("PartId");

                    b.ToTable("MS_PURCHASE_ITEM", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Review_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Review_Date");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Review_Text");

                    b.HasKey("ReviewId");

                    b.ToTable("MS_REVIEW", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleInvoice", b =>
                {
                    b.Property<int>("SaleInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Sale_Invoice_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaleInvoiceId"));

                    b.Property<DateTime?>("CreditDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Credit_Due_Date");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Discount_Amount");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Payment_Status");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Sale_Date");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("Staff_ID");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Total_Amount");

                    b.HasKey("SaleInvoiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("MS_SALE_INVOICE", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleInvoiceItem", b =>
                {
                    b.Property<int>("SaleInvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("Sale_Invoice_ID");

                    b.Property<int>("SaleItemId")
                        .HasColumnType("integer")
                        .HasColumnName("Sale_Item_ID");

                    b.HasKey("SaleInvoiceId", "SaleItemId");

                    b.HasIndex("SaleItemId");

                    b.ToTable("MS_SALE_INVOICE_ITEM", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleItem", b =>
                {
                    b.Property<int>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Sale_Item_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaleItemId"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("Part_ID");

                    b.Property<int>("SaleQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("Sale_Quantity");

                    b.Property<decimal>("SaleUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Sale_Unit_Price");

                    b.HasKey("SaleItemId");

                    b.HasIndex("PartId");

                    b.ToTable("MS_SALE_ITEM", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserAppointment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("Appointment_ID");

                    b.HasKey("UserId", "AppointmentId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("MS_USER_APPOINTMENT", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("Notification_ID");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("MS_USER_NOTIFICATION", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserPart", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("Part_ID");

                    b.HasKey("UserId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("MS_USER_PART", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserPartRequest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("Request_ID");

                    b.HasKey("UserId", "RequestId");

                    b.HasIndex("RequestId");

                    b.ToTable("MS_USER_PART_REQUEST", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserPurchaseInvoice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("Purchase_Invoice_ID");

                    b.HasKey("UserId", "PurchaseInvoiceId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("MS_USER_PURCHASE_INVOICE", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserReview", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer")
                        .HasColumnName("Review_ID");

                    b.HasKey("UserId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("MS_USER_REVIEW", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserSaleInvoice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("SaleInvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("Sale_Invoice_ID");

                    b.HasKey("UserId", "SaleInvoiceId");

                    b.HasIndex("SaleInvoiceId");

                    b.ToTable("MS_USER_SALE_INVOICE", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserVehicle", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("Vehicle_ID");

                    b.HasKey("UserId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MS_USER_VEHICLE", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserVendor", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("User_ID");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("Vendor_ID");

                    b.HasKey("UserId", "VendorId");

                    b.HasIndex("VendorId");

                    b.ToTable("MS_USER_VENDOR", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Vehicle_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Model");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Vehicle_Number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("Year");

                    b.HasKey("VehicleId");

                    b.HasIndex("VehicleNumber")
                        .IsUnique();

                    b.ToTable("MS_VEHICLE", (string)null);
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Vendor_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendorId"));

                    b.Property<string>("VendorAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Vendor_Address");

                    b.Property<string>("VendorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Vendor_Email");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Vendor_Name");

                    b.Property<string>("VendorPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Vendor_Phone");

                    b.HasKey("VendorId");

                    b.ToTable("MS_VENDOR", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedPurchaseInvoices")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.Vendor", "Vendor")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.PurchaseItem", "PurchaseItem")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("PurchaseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("PurchaseItem");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseItem", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.Part", "Part")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleInvoice", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "StaffUser")
                        .WithMany("StaffSaleInvoices")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleInvoiceItem", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.SaleInvoice", "SaleInvoice")
                        .WithMany("SaleInvoiceItems")
                        .HasForeignKey("SaleInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.SaleItem", "SaleItem")
                        .WithMany("SaleInvoiceItems")
                        .HasForeignKey("SaleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleInvoice");

                    b.Navigation("SaleItem");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.Part", "Part")
                        .WithMany("SaleItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserAppointment", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.Appointment", "Appointment")
                        .WithMany("UserAppointments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserAppointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserPart", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.Part", "Part")
                        .WithMany("UserParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserParts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserPartRequest", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.PartRequest", "PartRequest")
                        .WithMany("UserPartRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserPartRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserPurchaseInvoice", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("UserPurchaseInvoices")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserPurchaseInvoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserReview", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.Review", "Review")
                        .WithMany("UserReviews")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserSaleInvoice", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.SaleInvoice", "SaleInvoice")
                        .WithMany("UserSaleInvoices")
                        .HasForeignKey("SaleInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserSaleInvoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleInvoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserVehicle", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserVehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("UserVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.UserVendor", b =>
                {
                    b.HasOne("MotoSpares.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserVendors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoSpares.Domain.Entities.Vendor", "Vendor")
                        .WithMany("UserVendors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("CreatedPurchaseInvoices");

                    b.Navigation("StaffSaleInvoices");

                    b.Navigation("UserAppointments");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserPartRequests");

                    b.Navigation("UserParts");

                    b.Navigation("UserPurchaseInvoices");

                    b.Navigation("UserReviews");

                    b.Navigation("UserSaleInvoices");

                    b.Navigation("UserVehicles");

                    b.Navigation("UserVendors");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("UserAppointments");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Part", b =>
                {
                    b.Navigation("PurchaseItems");

                    b.Navigation("SaleItems");

                    b.Navigation("UserParts");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PartRequest", b =>
                {
                    b.Navigation("UserPartRequests");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseInvoiceItems");

                    b.Navigation("UserPurchaseInvoices");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.PurchaseItem", b =>
                {
                    b.Navigation("PurchaseInvoiceItems");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Review", b =>
                {
                    b.Navigation("UserReviews");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleInvoice", b =>
                {
                    b.Navigation("SaleInvoiceItems");

                    b.Navigation("UserSaleInvoices");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.SaleItem", b =>
                {
                    b.Navigation("SaleInvoiceItems");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("UserVehicles");
                });

            modelBuilder.Entity("MotoSpares.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("PurchaseInvoices");

                    b.Navigation("UserVendors");
                });
#pragma warning restore 612, 618
        }
    }
}
